version: "3.8"

services:

  front:
    image: node:alpine
    tty: true
    stdin_open: true
    working_dir: /usr/src/server
    volumes:
      - ./front:/usr/src/server
    ports:
      - ${PORT_FRONT}:${PORT_FRONT}

  back:
    image: node:alpine
    tty: true
    stdin_open: true
    working_dir: /usr/src/server
    volumes:
      - ./back:/usr/src/server
    ports:
        - ${PORT_BACK}:${PORT_BACK}

  database:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - target: 5432
        published: 5432
        protocol: tcp

